#!/bin/ksh

#
#
# Copyright (c) 2022 Piotr Trzpil  p.trzpil@protonmail.com
#
# Permission to use, copy, modify, and distribute 
# this software for any purpose with or without fee
# is hereby granted, provided that the above copyright
# notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR
# DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE
# FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF
# CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE
# OF THIS SOFTWARE.
#
#


gpsraw_dir='GPS_raw'
gpschk_dir='GPS_chk'
gpsopt_dir='GPS_opt'
gpsuniq_dir='GPS_uniq'
min_dist=15

nmeaprg='./readNMEA'

case $min_dist in '' | *[!0123456789]*)

     printf '%s\n' "$0: $min_dist: invalid digit" >&2; exit;;

esac

if ! test -d "$nmeaprg"
then

	if ! test -x "$nmeaprg"
	then

		printf "No readNMEA program, run sh install.sh first\n" 1>&2
		exit

	fi

fi

if ! test -d "$gpsuniq_dir"
then
	if test -e "$gpsuniq_dir"
	then
		
		printf "File %s already exists but is not directory\n" "$gpsuniq_dir" 1>&2
		printf "Please move it out from this path so this program\n" 1>&2
		printf "can use this name for path used by it\n" 1>&2
		exit

	fi

	printf "Creating directory %s\n" "$gpsuniq_dir"
	mkdir "$gpsuniq_dir"

fi


if ! test -d "$gpsopt_dir"
then
	if test -e "$gpsopt_dir"
	then
		
		printf "File %s already exists but is not directory\n" "$gpsopt_dir" 1>&2
		printf "Please move it out from this path so this program\n" 1>&2
		printf "can use this name for path used by it\n" 1>&2
		exit

	fi

	printf "Creating directory %s\n" "$gpsopt_dir"
	mkdir "$gpsopt_dir"

fi

if ! test -d "$gpschk_dir"
then
	if test -e "$gpschk_dir"
	then
		
		printf "File %s already exists but is not directory\n" "$gpschk_dir" 1>&2
		printf "Please move it out from this path so this program\n" 1>&2
		printf "can use this name for path used by it\n" 1>&2
		exit

	fi

	printf "Creating directory %s\n" "$gpschk_dir"
	mkdir "$gpschk_dir"

fi

if ! test -d "$gpsraw_dir"
then
	if test -e "$gpsraw_dir"
	then
		
		printf "File %s already exists but is not directory\n" "$gpsraw_dir" 1>&2
		printf "Please move it out from this path so this program\n" 1>&2
		printf "can use this name for path used by it\n" 1>&2
		exit

	fi

	printf "Creating directory %s\n" "$gpsraw_dir"
	mkdir "$gpsraw_dir"

fi

tempfile="$( mktemp )"

printf "Coping missing directories from GPS_raw directory,\n"
printf "to GPS_opt and GPS_chk directories\n"
if find "$gpsraw_dir"'/'* -type d > "$tempfile" 2>/dev/null
then

	while read -r line
	do
		name="$gpschk_dir"'/'"${line#*/}"
		mkdir -p "$name" 2>/dev/null

		name="$gpsopt_dir"'/'"${line#*/}"
		mkdir -p "$name" 2>/dev/null

		name="$gpsuniq_dir"'/'"${line#*/}"
		mkdir -p "$name" 2>/dev/null

	done < "$tempfile"

fi

./chkscript "$gpsraw_dir" "$gpschk_dir" 2> chklog

./optscript "$gpschk_dir" "$gpsopt_dir" "$min_dist"

./uniqscript "$gpsopt_dir" "$gpsuniq_dir"

printf "\nGPS_uniq single lined and empty files cleanup\n"

find "$gpsuniq_dir" -type f -iname '*.log' > "$tempfile"
while IFS= read -r line
do

	linenum=$( cat "$line" | wc -l | tr -d '[:blank:]' )
	if (( "$linenum" < 2 ))
	then
		rm -v "$line"
	fi

done < "$tempfile"

printf "\nFinished !!!\n"

rm -f "$tempfile"
